# Generated by Django 3.2.4 on 2021-07-26 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='description',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='title',
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
